[package]
name = "smtp-high-level"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.11.4"
mail-send = "0.4.7"
futures = "0.3.30"
